name: Test Schedule

on:
  schedule:
  - cron: '0 23 * * 0-4' # 2300 UTC == 0900 AEST
  - cron: '0 22 * * 0-4' # 2200 UTC == 0900 AEDT

jobs:
  check-dst:
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.which_schedule.outputs.time }}
    steps:
    # Will be blank when DST changes
    - name: Is Expected Schedule
      id: which_schedule
      shell: bash
      run: |
        echo ::set-output name=time::"$(TZ=Australia/Melbourne date | grep '09:..:..' || true)"
  
  action-to-run:
    runs-on: ubuntu-latest
    needs: check-dst
    if: needs.check-dst.outputs.time != ''
    steps:
    - name: Action
      run: echo "this will only run when expected dst cron matches"
